services:
  osrm:
    build: .
    volumes:
      - ./data:/data
    entrypoint: >
      sh -c "
        osrm-extract -p /opt/car.lua /data/iran-latest.osm.pbf &&
        osrm-partition /data/iran-latest.osrm &&
        osrm-customize /data/iran-latest.osrm &&
        osrm-routed --algorithm mld /data/iran-latest.osrm
      "
    ports:
      - "5000:5000"
